name: Build snapshot reusable workflow

on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string
      docker_image_name:
        required: true
        type: string
      maven_internal-apis_repo_url:
        required: true
        type: string
      sonar_project_key:
        required: true
        type: string
    secrets:
      ACCESS_TOKEN:
        required: true
      SONAR_TOKEN:
        required: true
      GIT_PACKAGES_USER:
        required: true
      GITHUB_TOKEN:
        required: true
    # Du kannst hier weitere secrets definieren, die der Workflow braucht

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          check-latest: true
          cache: maven

      - name: maven-settings
        uses: s4u/maven-settings-action@v3.1.0
        with:
          servers: |
            [{
                "id": "github",
                "username": "${{ github.repository_owner }}",
                "password": "${{ secrets.ACCESS_TOKEN }}"
            }]
          repositories: |
            [{
              "id": "github2",
              "name": "github2",
              "url": "${{ inputs.maven_internal-apis_repo_url }}",
              "snapshots": { "enabled": true }
            }]
          githubServer: false

      - name: Build and test
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn clean package verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=${{ inputs.sonar_project_key }}

      - name: Get the version
        id: tag
        run: echo "VERSION=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        run: docker buildx create --use

      - name: Build Docker image
        working-directory: ./
        env:
          GITHUB_ACTOR: ${{ secrets.GIT_PACKAGES_USER }}
          GITHUB_OWNER: ${{ github.repository_owner }}
          GIT_PACKAGE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          ACTUAL_TAG: ${{ env.VERSION }}
        run: |
          docker login ghcr.io/$GITHUB_ACTOR -u=$GITHUB_ACTOR -p=$GIT_PACKAGE_PASSWORD
          docker buildx build --platform linux/arm64,linux/amd64 -t ghcr.io/$GITHUB_OWNER/${{ inputs.docker_image_name }}:$ACTUAL_TAG --push .

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
