name: Release main reusable workflow

on:
  workflow_call:
    inputs:
      release_tag:
        required: true
        type: string
      docker_image_name:
        required: true
        type: string
      maven_internal-apis_repo_url:
        required: true
        type: string
    secrets:
      ACCESS_TOKEN:
        required: true

env:
  REGISTRY: ghcr.io

jobs:
  build-java-maven-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: maven-settings
        uses: s4u/maven-settings-action@v3.1.0
        with:
          servers: |
            [{
                "id": "github",
                "username": "${{ github.repository_owner }}",
                "password": "${{ secrets.ACCESS_TOKEN }}"
            },
            {
                "id": "github2",
                "username": "${{ github.repository_owner }}",
                "password": "${{ secrets.ACCESS_TOKEN }}"
            }]
          repositories: '[{"id":"github2","name":"github2","url":"${{ inputs.maven_internal-apis_repo_url }}","snapshots":{"enabled":true}}]'
          githubServer: false

      - name: Configure git
        run: |
          git config --global committer.email "noreply@github.com"
          git config --global committer.name "GitHub"
          git config --global author.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global author.name "${GITHUB_ACTOR}"

      - name: Checkout main branch
        run: git checkout main

      - name: Prepare release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn --batch-mode release:prepare -DreleaseVersion=${{ inputs.release_tag }} -Dusername=$GITHUB_ACTOR -Dpassword=$GITHUB_TOKEN

      - name: get-pom-version
        id: pom-version
        run: echo "version=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        run: docker buildx create --use

      - name: Build Docker image
        working-directory: ./
        env:
          GITHUB_ACTOR: ${{ secrets.GIT_PACKAGES_USER }}
          GIT_PACKAGE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REGISTRY: ${{ env.REGISTRY }}
          ACTUAL_TAG: ${{ inputs.release_tag }}
        run: |
          docker login ghcr.io/$GITHUB_ACTOR -u=$GITHUB_ACTOR -p=$GIT_PACKAGE_PASSWORD
          docker buildx build --platform linux/arm64,linux/amd64 -t ghcr.io/$GITHUB_ACTOR/${{ inputs.docker_image_name }}:$ACTUAL_TAG -t ghcr.io/$GITHUB_ACTOR/${{ inputs.docker_image_name }}:latest --push .

      - name: Perform release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn --batch-mode release:perform -Dusername=$GITHUB_ACTOR -Dpassword=$GITHUB_TOKEN